name: CI/CD Pipeline Monster Trends

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Go application
        run: |
          go mod tidy
          go build -o webapp-monster ./cmd/webapp

      - name: Docker Login to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Building and deploying monster trends application..."
            mkdir -p /home/deploy/monster-trends
            cd /home/deploy/monster-trends

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./webapp-monster"
          target: "/home/deploy/monster-trends"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/deploy/monster-trends
            sudo docker stop monster-trends || true
            sudo docker rm monster-trends || true
            sudo docker rmi monster-trends-image || true
            sudo docker build -t monster-trends-image .
            sudo docker run -d --name monster-trends -p 8080:8080 monster-trends-image